name: "validate index definition"
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, closed]

jobs:
  validate-index:
    runs-on: ubuntu-latest
    steps:
      - name: Runs Elasticsearch
        uses: elastic/elastic-github-actions/elasticsearch@master
        with:
          stack-version: 8.4.0
          security-enabled: false
      
      - uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v2

      - name: Run Terraform init
        id: init
        run: terraform init -no-color
        working-directory: terraform/elastic
      
      - name: Run Terraform apply
        run: terraform apply -auto-approve -input=false
        id: apply
        working-directory: ./terraform/elastic
